### ISSUE TITLE
Command tail does not work

### ISSUE THREAD

**Issue by 2byte** [LaravelCollective/remote#8]
Laravel 5
```
root@ubuntu:/mnt/hgfs/Ubuntu/projects.dev/pamani# php artisan tail
#38 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /mnt/hgfs/Ubuntu/projects.dev/pamani/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(115): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /mnt/hgfs/Ubuntu/projects.dev/pamani/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 /mnt/hgfs/Ubuntu/projects.dev/pamani/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}  
tail: невозможно определить расположение «/mnt/hgfs/Ubuntu/projects.dev/pamani/storage/logs/laravel-2015-05-02.log», возвращаемся к методу опросом: Ошибка ввода/вывода
```

```
root@ubuntu:/mnt/hgfs/Ubuntu/projects.dev/pamani# php artisan tail --path=storage/logs/ssh.log
tail: невозможно открыть «» для чтения: Нет такого файла или каталога
У вас есть новая почта в /var/mail/root
root@ubuntu:/mnt/hgfs/Ubuntu/projects.dev/pamani# php artisan tail --path=/mnt/hgfs/Ubuntu/projects.dev/pamani/storage/logs/ssh.log
tail: невозможно открыть «» для чтения: Нет такого файла или каталога
root@ubuntu:/mnt/hgfs/Ubuntu/projects.dev/pamani# 
```

**Comment by tshafer** [comment]
What version of laravel?



—
Tom Shafer

**Comment by 2byte** [comment]
Last

**Comment by adamgoose** [comment]
Unfortunately, we are unable to read your stack trace because it is in Russian. Can you please change the locale on your computer to English, and try again?

**Comment by 2byte** [comment]
```
tail: невозможно определить расположение «/mnt/hgfs/Ubuntu/projects.dev/pamani/storage/logs/laravel-2015-05-02.log», возвращаемся к методу опросом: Ошибка ввода/вывода
```
```
Unable to determine location /mnt/hgfs/Ubuntu/projects.dev/pamani/storage/logs/laravel-2015-05-02.log returning to votes: error input/output

**Comment by 2byte** [comment]
If using `--path=/mnt/hgfs/Ubuntu/projects.dev/pamani/storage/logs/deploy.log` 
```
Unable to open "" for read: No such file or directory
```
